# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b216a0dc17e7d8adc3b5ec3c7de3d86acfe5eb26c17324ca0f411891cb8c0a998e44e90bd68a7f353062ca1c852a5a4464a3d5ef9eb4f79d75761fa65e69d3dc

test:
  secret_key_base: 6b67097b90f47d44d5c54e89fe3735056168c30b23f84a0d3566a105fe511959911be04875b0ac7d9fca96acc1b5492ae44cf65fef6e9e250a9ee42b713ee63c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
